package com.example.Student_Library_Management_System.Services;

import com.example.Student_Library_Management_System.DTOs.StudentUpdateMobRequestDto;
import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentServices {
    @Autowired
    StudentRepository studentRepository;
    public String createStudent(Student student){
          // Student from the postman is already the basicc attributes set

        // card should be autogenerated when createStudent function is called
        Card card = new Card();
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudent(student); // foreign key attribute value yaha se ayega

        // let's go to student
        student.setCard(card);

        // if there was unidirectional mapping we had to save both of them,
        // but we used biderctional so child will automatically saved.

        studentRepository.save(student);
        //by cascading effect , child will automaticallly saved.

        return "STudent and card added";

    }

    public String  findNameByEmail(String email){
        Student student = studentRepository.findByEmail(email);
        return student.getName();
    }

    public String updateMobNo(StudentUpdateMobRequestDto studentReq){
        //convert the DTO to Entity.


        // first we fetch originaldata

        Student originalStudent = studentRepository.findById(studentReq.getId()).get();
        // we will keep the other properties as it is : and only change the req parameters

        originalStudent.setMobNo(studentReq.getMobNo());
      // always the entity obj is being saved.


        studentRepository.save(originalStudent);
        return  "Updsted success";
    }

//    1. existing functions with no definition;
//     2. existing with definition ;
//     3. write own query

}
